// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs3iBjJ5DioEGYR7VfP3HfmmY77v46JxY',
    appId: '1:200302669943:web:ce91d5c25d026dddb21672',
    messagingSenderId: '200302669943',
    projectId: 'flutterapp-b3a45',
    authDomain: 'flutterapp-b3a45.firebaseapp.com',
    storageBucket: 'flutterapp-b3a45.appspot.com',
    measurementId: 'G-6G007V2KL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCBiGAe3gwjScqu-ChM2V12VKO7xtopY0',
    appId: '1:200302669943:android:e05b7584b77be618b21672',
    messagingSenderId: '200302669943',
    projectId: 'flutterapp-b3a45',
    storageBucket: 'flutterapp-b3a45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJRI9GxsPYgTQ6ZKIGYj7MQn48hIpoCHI',
    appId: '1:200302669943:ios:63ed6ac0e77f3b37b21672',
    messagingSenderId: '200302669943',
    projectId: 'flutterapp-b3a45',
    storageBucket: 'flutterapp-b3a45.appspot.com',
    iosClientId: '200302669943-pkgekuurg194o396stooestf7ojegov9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJRI9GxsPYgTQ6ZKIGYj7MQn48hIpoCHI',
    appId: '1:200302669943:ios:63ed6ac0e77f3b37b21672',
    messagingSenderId: '200302669943',
    projectId: 'flutterapp-b3a45',
    storageBucket: 'flutterapp-b3a45.appspot.com',
    iosClientId: '200302669943-pkgekuurg194o396stooestf7ojegov9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileProject',
  );
}
